# Maven

# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

pr:
  - main
  - releases/*
  
trigger:
- main

strategy:
  matrix:
    jdk10_linux:
      imageName: "ubuntu-latest"
      jdkVersion: "1.10"
    jdk11_windows:
      imageName: "windows-latest"
      jdkVersion: "1.11"
  maxParallel: 2

pool:
  vmImage: $(imageName)

steps:
- task: Maven@4
  inputs:
    mavenPomFile: "pom.xml"
    mavenOptions: "-Xmx3072m"
    javaHomeOption: "JDKVersion"
    jdkVersionOption: $(jdkVersion)
    jdkArchitectureOption: "x64"
    publishJUnitResults: true
    testResultsFiles: "**/TEST-*.xml"
    goals: "package"

- task: ServiceNow-DevOps-Server-Change-Acceleration@1
  inputs:
    connectedServiceName: 'ServiceNow ITSM Pro Demo service connection'
    changeRequestDetails: |
      {
          "setCloseCode" : true,
          "attributes": {
- task: ServiceNow-DevOps-Server-Change-Acceleration@1
  inputs:
    connectedServiceName: 'ServiceNow ITSM Pro Demo service connection'
    changeRequestDetails: |
      {
          "setCloseCode" : true,
          "attributes": {
            "requested_by": {
              "name": "Azure Devops test user"
            },
            "start_date": "2021-01-05 08:00:00",
            "end_date": "2021-01-08 08:00:00"
          }
        }
            "requested_by": {
              "name": "test Azure Devops user"
            },
            "start_date": "2023-07-09 08:00:00",
            "end_date": "2023-07-09 08:00:00"
          }
        }