# Maven

# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

pr:
  - main
  - releases/*
  
trigger:
- main

stages:
- stage: ServiceNowDev
  displayName: 'Deploy to Dev'
  jobs:
  - job: deploy_infratsructure
    displayName: Deploy to Dev
    strategy:
      matrix:
        jdk10_linux:
          imageName: "ubuntu-latest"
          jdkVersion: "1.10"
        jdk11_windows:
          imageName: "windows-latest"
          jdkVersion: "1.11"
      maxParallel: 1
    pool:  
      vmImage: $(imageName)
    steps:
      - task: Maven@4
        inputs:
          mavenPomFile: "pom.xml"
          mavenOptions: "-Xmx3072m"
          javaHomeOption: "JDKVersion"
          jdkVersionOption: $(jdkVersion)
          jdkArchitectureOption: "x64"
          publishJUnitResults: true
          testResultsFiles: "**/TEST-*.xml"
          goals: "package"
  - job: 'ServiceNowChangeRecord'
    displayName: 'Trigger Change Record'
    dependsOn:
    - deploy_infratsructure
    condition: succeeded()
    pool:
      name: Server
    steps:
      - task: UpdateServiceNowChangeRequest@2
        inputs:
          ServiceNowConnection: 'ITSM Pro - ServiceNow service connection'
          ChangeRequestNumber: 'CHG0000014'
          NewStatus: '-4'
          WorkNotes: 'state is now updated via Azure Devops Pipeline!'