# Maven

# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

pr:
  - main
  - releases/*
  
trigger:
- main

stages:
- stage: ServiceNowDev
  displayName: 'Deploy to Dev'
  jobs:
  - job: 'ServiceNowChangeRecord'
    displayName: 'Trigger Change Record through DevOps'
    dependsOn:
    - deploy_infratsructure
    condition: succeeded()
    pool:
      name: Server
    steps:
      - task: ServiceNow-DevOps-Server-Change-Acceleration@1
        inputs:
          connectedServiceName: 'ServiceNow ITSM Pro Demo service connection'
          changeRequestDetails: |
            {
                "setCloseCode" : true,
                "attributes": {
                  "requested_by": {
                    "user_name": "abel.tuter"
                  },
                  "start_date": "2021-01-05 08:00:00",
                  "end_date": "2021-01-08 08:00:00"
                }
              }